### ISSUE TITLE
Install Button is disabled

### ISSUE THREAD

**Issue by mtshrmn** [Goobwabber/LegacyInstaller#13]
The install button (`installButton`) is disabled even when everything seems to be ok.

Steps to reproduce:
1. Launch steam
2. Update beat saber to 1.20 (latest version as the time writing this)
3. Open LegacyInstaller
4. Select paths (See Image)

![image](https://user-images.githubusercontent.com/18540571/157866625-0afaa39d-742f-4f54-9cf9-6af84e39cf5a.png)

I'm expecting the Install button to be enabled and let me press it to install once all the info is filled in.

P.S. Thank you for working on this project! I'm not experienced with C# and windows in general, otherwise I would've submitted a PR myself (or update the readme in case I'm doing something dumb here).

**Comment by FireWolf-kPanel** [comment]
Same here. doesn't work.

![image](https://user-images.githubusercontent.com/62524520/158019151-0ed8b280-600f-486b-9619-9c1ca3c5ab3b.png)

**Comment by Goobwabber** [comment]
fixed by #14
