### ISSUE TITLE
[Feature] Maybe make a button that just adds the game to steam without Downloading the game Completely

### ISSUE THREAD

**Issue by XCraftTM** [Goobwabber/LegacyInstaller#7]
Maybe make a button that just adds the game to steam without Downloading the game Completely, because i have already downloaded the game and now it just downloads it again for no reason. Or is there any way to skip the download?

**Comment by MichaelGatesDev** [comment]
I'm not quite sure what you're asking. The contents of the game are different between the different versions. The version you are downgrading to by using this tool has different contents than what you currently have installed, so therefore the game must be re-downloaded .
